version: '3.8'

services:
  caipincheck:
    build:
      context: .
    ports:
      - "3001:3001"
    volumes:
      - ./food-check.db:/app/food-check.db
    restart: always
    environment:
      NODE_ENV: production
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
