version: '3.8'

services:
  caipincheck:
    build:
      context: .
      args:
        VITE_DEEPSEEK_API_KEY: ${VITE_DEEPSEEK_API_KEY}
    ports:
      - "3001:3001"
    volumes:
      - ./food-check.db:/app/food-check.db
    restart: always
    environment:
      NODE_ENV: production
      VITE_DEEPSEEK_API_KEY: ${VITE_DEEPSEEK_API_KEY}
